name: 'Publish'
on:
  pull_request:
     branches:
       - main

jobs:
  build:
    name:  Publish 
    runs-on: ubuntu-latest

    env:
      environmentName: Prod
    
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          repo-token: ${{ github.token }}

    - name: Publish in powershellgallery
      shell: pwsh
      env:
        APIKEY: ${{ secrets.APIKEY }}
        PATH: ${{ github.workspace }}
      run: |
          ls ${{ github.workspace }}
          ${{ github.workspace }}\powershellgallery\publish.ps1