name: 'Publish'
on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  build:
    if:  "!startsWith(github.head_ref, 'docs/')"
    name:  Publish 
    runs-on: ubuntu-latest

    env:
      environmentName: Prod
    
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          repo-token: ${{ github.token }}

    - name: Publish in powershellgallery
      shell: pwsh
      env:
        APIKEY: ${{ secrets.APIKEY }}
        AZ: ${{ github.workspace }}
      run: |
          ${{ github.workspace }}\powershellgallery\publish.ps1
